server:
  address: 0.0.0.0
  port: 8085
  servlet:
    application-display-name: Agricon
    context-path: /

recaptcha:
  site: https://www.google.com/recaptcha/api/siteverify
  key: 6Lf0xUkbAAAAAG-oFr1LloawlDuXWV3MksgrF6Ih
  secret: 6Lf0xUkbAAAAADu0F6DePF06GKTYKU_HsM_dt8Vz

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  mail:
    host: mail.agricon.uk
    username: info@agricon.uk
    password: zM63Mwqmn6
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587